### ISSUE TITLE
Multiple exceptions caused by infinity loops

### ISSUE THREAD

**Issue by Sasorien** [OlivierMary/aw-watcher-jetbrains#28]
**Exception in Plugin Activity Watcher (1.0.8)**

This Error Message comes up regularly in my IntelliJ Ultimate 2019.2.3. 
This curse might be different, but it always end up in an infinity loop in the NetworkInterceptorChain of the HttpEngine. Didnt look up the code though.
Here some snippets of the stacktraces:

```
java.lang.StackOverflowError
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.connection(HttpEngine.java:663)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:675)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
....
```

```
java.lang.StackOverflowError
	at com.squareup.okhttp.internal.http.StreamAllocation.connection(StreamAllocation.java:211)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.connection(HttpEngine.java:663)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:675)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
....
```

```
java.lang.StackOverflowError
	at com.squareup.okhttp.OkHttpClient.networkInterceptors(OkHttpClient.java:556)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:674)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
....
```

```
java.lang.StackOverflowError
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:674)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
....
```

```
java.lang.StackOverflowError
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:671)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
....
```

```
java.lang.StackOverflowError
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:674)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
....
```

```
java.lang.StackOverflowError
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at okio.Okio$1.write(Okio.java:80)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:221)
	at com.squareup.okhttp.internal.http.Http1xStream$FixedLengthSink.flush(Http1xStream.java:294)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:223)
	at okio.ForwardingSink.flush(ForwardingSink.java:39)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:223)
	at org.openapitools.client.ProgressRequestBody.writeTo(ProgressRequestBody.java:56)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:718)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
	at org.openapitools.client.api.DefaultApi$46.intercept(DefaultApi.java:1457)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
....
```

**Comment by OlivierMary** [comment]
Hi,

Can you see activity on activity watch ?

**Comment by Sasorien** [comment]
Not for IntelliJ.
If i want to show the values for today (2019-11-11) i get timeout errors on some pages in the activity watch dashboard. Values for yesterday are working. But that has nothing to do with this plugin i think.

I've just downloaded the bucket and a quick search results in no entries since 2019-11-05. 
Perhabs the day i reinstalled the plugin again since half a year ago or so. That time the plugin results in crashes for intelliJ therefore i disabled it.

**Comment by OlivierMary** [comment]
Activity watch server in which version ??

**Comment by Sasorien** [comment]
Version: v0.8.0b8

For Version: v0.8.0b9 there is no changelog entry in https://activitywatch.readthedocs.io/en/latest/changelog.html

**Comment by Sasorien** [comment]
oh i see v0.8.1 was released some minutes ago... 
https://github.com/ActivityWatch/activitywatch/releases/tag/v0.8.1

**Comment by OlivierMary** [comment]
@Sasorien any news ?
